# Generated by Django 4.1.7 on 2023-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="comments",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
