# Generated by Django 4.1.7 on 2023-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0002_todoitem_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
